swagger: "2.0"
info:
  description: "My Game Server"
  version: 1.0.0
  title: "My Game Server"
  contact:
    email: "daikikobayashi1910@gmail.com"
host: "localhost:8000"
basePath: "/v1"

tags:
  - name: Master
    description: "Master Data"
  - name: Player
    description: "Player specific requests"
schemes:
  - "http"
paths:
  /registerAccount:
    post:
      tags:
      - "player"
      summary: "RegisterAccount"
      description: "RegisterAccount"
      operationId: "registerAccount"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/RegisterAccountRequest"
      responses:
        "200":
          description: ""
          schema:
            $ref: "#/definitions/RegisterAccountResutlt"
        "405":
          description: "Invalid input"
      security:
        - api_key: []
                

definitions:
  RegisterAccountRequest:
    type: object
    properties:
      request_id:
        type: "integer"
        format: "int64"

  RegisterAccountResutlt:
    type: object
    properties:
      uuid:
        type: "string"

  PlayerLevelMaster:
    type: object
    properties:
      id:
        type: "integer"
        format: "int64"
        x-nullable: false
      level:
        type: "integer"
        format: "int64"
      exp:
        type: "integer"
        format: "int64"

  CardLevelMaster:
    type: object
    properties:
      id:
        type: "integer"
        format: "int64"
        x-nullable: false
      level:
        type: "integer"
        format: "int64"
      rank:
        type: "integer"
        format: "int64"
      exp:
        type: "integer"
        format: "int64"